# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2020-07-14 07:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_todolist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Access',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('permission_type', models.CharField(max_length=30)),
                ('list_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.TodoList')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.user')),
            ],
        ),
    ]
