# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2020-07-14 07:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_access'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoItem',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('heading', models.CharField(max_length=30)),
                ('scheduled_on', models.DateTimeField(auto_now_add=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('list_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.TodoList')),
            ],
        ),
    ]
